Repository MiniProject-2/need-more-task-fe, pull requests merged in 2023-05, with the labels that each got.

#11 [공통적용] #9
  .gitignore
  next.config.js
  package.json
  src/components/Auth/Join.tsx
  src/components/Auth/TitleLabel.tsx
  src/components/ChakraProviders/index.tsx
  src/hooks/useDebounce.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/join.tsx
  src/styles/auth.styles.ts
  src/styles/customTheme.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: enhancement

#15 feat: Layout 가운데 정렬 수정
  src/components/Layout.tsx
Labels: enhancement

#16 회원가입 페이지 StepOne, Two, Three
  public/svg/arrow-bottom.svg
  public/svg/step1-active.svg
  public/svg/step1-disabled.svg
  public/svg/step2-active.svg
  public/svg/step2-disabled.svg
  public/svg/step3-active.svg
  public/svg/step3-disabled.svg
  public/svg/step4-active.svg
  public/svg/step4-disabled.svg
  src/components/Auth/AuthInput.tsx
  src/components/Auth/FooterLabel.tsx
  src/components/Auth/Join.tsx
  src/components/Auth/Join/JoinLayout.tsx
  src/components/Auth/Join/StepOne.tsx
  src/components/Auth/Join/StepThree.tsx
  src/components/Auth/Join/StepTwo.tsx
  src/components/Auth/PasswordInput.tsx
  src/components/Auth/SelectDepartment.tsx
  src/components/Auth/UploadImage.tsx
  src/hooks/useDebounce.ts
  src/hooks/useInput.ts
  src/pages/join/[step].tsx
  src/pages/join/complete.tsx
  src/store/userJoinStore.ts
  src/styles/auth.styles.ts
  src/styles/reset.css
  src/utils/index.ts
Labels: enhancement

#22 회원가입, post mock server api 추가
  next.config.js
  package.json
  public/lottie/welcome.json
  src/apis/configs/index.ts
  src/apis/user.ts
  src/components/Auth/AuthInput.tsx
  src/components/Auth/AuthNumberInput.tsx
  src/components/Auth/Join/StepThree.tsx
  src/components/Auth/Join/StepTwo.tsx
  src/components/Auth/PasswordInput.tsx
  src/components/CommonHeader/CommonHeader.tsx
  src/components/CommonHeader/ProfileImage.tsx
  src/components/Layout.tsx
  src/hooks/LottieAni.tsx
  src/pages/join/complete.tsx
  src/store/userJoinStore.ts
  src/styles/auth.styles.ts
  src/styles/commonHeader.styles.ts
  src/type/authTypes.ts
Labels: enhancement

#27 [프로필 페이지, 로그인] 프로필 수정 기능/로그인
  public/png/mysql.png
  src/apis/user.ts
  src/components/Auth/AuthUser.tsx
  src/components/Auth/FooterLabel.tsx
  src/components/Auth/Join.tsx
  src/components/Auth/Join/JoinLayout.tsx
  src/components/Auth/Join/LoginLayout.tsx
  src/components/Auth/Join/StepThree.tsx
  src/components/Auth/Join/StepTwo.tsx
  src/components/Auth/Login.tsx
  src/components/CommonHeader/CommonHeader.tsx
  src/components/Profile/index.tsx
  src/pages/CalendarPage.jsx
  src/pages/_app.tsx
  src/pages/join.tsx
  src/pages/join/complete.tsx
  src/pages/login.tsx
  src/pages/profile/[id].tsx
  src/store/acceessTokenStore.ts
  src/store/userInfoStore.ts
  src/store/userJoinStore.ts
  src/styles/commonHeader.styles.ts
  src/styles/profile.styles.ts
  src/type/authTypes.ts
Labels: enhancement

#35 [프로필 수정, 대시보드 페이지]
  public/lottie/noProjects.json
  public/svg/draw.svg
  public/svg/figma.svg
  public/svg/github.svg
  src/apis/configs/index.ts
  src/apis/dashboard.ts
  src/apis/user.ts
  src/components/Auth/Join/StepThree.tsx
  src/components/Auth/Login.tsx
  src/components/CommonAvatar/CommonAvatar.tsx
  src/components/CommonHeader/CommonHeader.tsx
  src/components/CommonHeader/LogoutModal.tsx
  src/components/Dashboard/DashboardBody.tsx
  src/components/Dashboard/DashboardFooter.tsx
  src/components/Dashboard/EmptyProjects.tsx
  src/components/Dashboard/LatestProjects.tsx
  src/components/Dashboard/LatestProjectsList.tsx
  src/components/Dashboard/PerformanceGraph.tsx
  src/components/Dashboard/SVGImage.tsx
  src/components/Dashboard/TaskProjectsPerformance.tsx
  src/components/Dashboard/TaskStatus.tsx
  src/components/Dashboard/TaskStatusGraph.tsx
  src/components/Dashboard/TaskStatusList.tsx
  src/components/Profile/CheckPasswordModal.tsx
  src/components/Profile/index.tsx
  src/components/common/CommonSpinner.tsx
  src/pages/dashboard/index.tsx
  src/pages/profile/[id].tsx
  src/store/acceessTokenStore.ts
  src/store/userInfoStore.ts
  src/store/userJoinStore.ts
  src/styles/dashboard.styles.ts
  src/styles/profile.styles.ts
  src/type/authTypes.ts
  src/type/dashBoardTypes.ts
Labels: enhancement

#36 feat: axiosWithToken JSON.parse 추가
  src/apis/configs/index.ts
Labels: enhancement

#38 fix: axiosWithToken.interceptors 타입 에러 수정
  src/apis/configs/index.ts
  src/pages/kanban.tsx
Labels: enhancement

#40 [hotfix] kanban 보드에서 발생한 에러 수정
  src/apis/configs/index.ts
  src/constant/TaskOverview.ts
  src/pages/kanban.tsx
Labels: bug

#44 [유저 권한 수정 페이지, endpoint 수정]
  .env.production
  next.config.js
  package.json
  src/apis/configs/index.ts
  src/apis/user.ts
  src/components/Admin/Admin.tsx
  src/components/Auth/AuthUser.tsx
  src/components/Auth/Join/JoinBackButton.tsx
  src/components/Auth/Join/JoinLayout.tsx
  src/components/Auth/Join/StepOne.tsx
  src/components/Auth/Join/StepThree.tsx
  src/components/Auth/Join/StepTwo.tsx
  src/components/CommonHeader/CommonHeader.tsx
  src/components/Dashboard/DashboardBody.tsx
  src/components/Profile/index.tsx
  src/constant/UserRole.ts
  src/pages/admin.tsx
  src/pages/join/complete.tsx
  src/pages/profile/[id].tsx
  src/styles/admin.styles.ts
  src/styles/auth.styles.ts
  src/styles/dashboard.styles.ts
  src/type/authTypes.ts
  src/utils/index.ts
Labels: enhancement

#45 fix: Content-Type, teamOptions value 수정
  .env.development
  src/apis/user.ts
  src/utils/index.ts
Labels: enhancement

#46 fix: [로그인, 회원가입] accessToken 전달 방식 수정
  src/apis/configs/index.ts
  src/apis/user.ts
  src/components/Auth/Join/StepThree.tsx
  src/components/Auth/Login.tsx
  src/store/acceessTokenStore.ts
  src/store/userJoinStore.ts
Labels: enhancement

#49 [프로필 페이지, 회원가입/로그인 페이지, 대시보드, 유저 권한 수정 페이지] 실제 api 적용
  src/apis/user.ts
  src/components/Admin/Admin.tsx
  src/components/Admin/UserRolePopover.tsx
  src/components/Auth/AuthUser.tsx
  src/components/Auth/Join/StepThree.tsx
  src/components/Auth/Login.tsx
  src/components/CommonAvatar/CommonAvatar.tsx
  src/components/CommonHeader/CommonHeader.tsx
  src/components/Dashboard/LatestProjectsList.tsx
  src/components/Dashboard/PerformanceGraph.tsx
  src/components/Dashboard/TaskStatusList.tsx
  src/components/Profile/CheckPasswordModal.tsx
  src/components/Profile/ProfileAccountInfo.tsx
  src/components/common/CommonToast.tsx
  src/constant/TaskOverview.ts
  src/pages/dashboard/index.tsx
  src/pages/profile/[id].tsx
  src/styles/admin.styles.ts
  src/styles/dashboard.styles.ts
  src/styles/emotion.d.ts
  src/styles/theme.ts
  src/utils/index.ts
Labels: enhancement

#53 일정 상세보기 상태관리, 스타일 개선, 달력, 페이지 타이틀 변경, 코드 리팩토링
  src/components/Calendar/CalendarView.tsx
  src/components/CommonHeader/CommonHeader.tsx
  src/components/OverView/Content.tsx
  src/components/OverView/Header.tsx
  src/pages/calendar/index.tsx
  src/pages/index.tsx
  src/pages/task/index.tsx
  src/store/overViewStore.ts
  src/styles/calendar.styles.ts
  src/styles/overview.styles.ts
  src/type/componentProps.ts
Labels: enhancement

#55 [프로필 페이지, 유저 권한 수정 페이지, 회원가입 페이지]
  next.config.js
  public/lottie/noUsers.json
  src/apis/user.ts
  src/components/Admin/Admin.tsx
  src/components/Admin/SelectedRoleUserList.tsx
  src/components/Admin/UserInfoPopover.tsx
  src/components/Admin/UserRoleSelectPopover.tsx
  src/components/Auth/Join/StepThree.tsx
  src/components/Auth/Join/StepTwo.tsx
  src/components/Auth/Login.tsx
  src/components/CommonHeader/CommonHeader.tsx
  src/components/CommonHeader/ProfileImage.tsx
  src/components/Dashboard/LatestProjects.tsx
  src/components/Dashboard/LatestProjectsList.tsx
  src/components/Profile/ProfileAccountInfo.tsx
  src/components/common/CommonEmptyProjects.tsx
  src/components/common/CommonEmptyUser.tsx
  src/pages/profile/[id].tsx
  src/store/userJoinStore.ts
  src/styles/admin.styles.ts
  src/styles/auth.styles.ts
  src/styles/commonHeader.styles.ts
  src/styles/profile.styles.ts
  src/type/authTypes.ts
Labels: enhancement

#62 일정 선택 기능 추가, 코드 및 스타일 개선, 사이드 바 컴포넌트 추가
  src/apis/overview.ts
  src/components/Calendar/CalendarView.tsx
  src/components/Drawer/index.tsx
  src/components/OverView/Content.tsx
  src/components/OverView/Header.tsx
  src/pages/calendar/index.tsx
  src/pages/tasks/index.tsx
  src/pages/tasks/period.tsx
  src/store/sideBarStore.ts
  src/styles/calendar.styles.ts
  src/styles/overview.styles.ts
  src/type/componentProps.ts
Labels: enhancement

#63 fix: [프로필 수정 페이지, 비회원 접근 차단, 이메일 중복 체크 로직 수정]
  src/components/Admin/Admin.tsx
  src/components/Admin/SelectedRoleUserList.tsx
  src/components/Admin/UserInfoPopover.tsx
  src/components/Auth/AuthInput.tsx
  src/components/Auth/AuthUser.tsx
  src/components/Auth/Join/StepOne.tsx
  src/components/Auth/Join/StepThree.tsx
  src/components/Auth/Join/StepTwo.tsx
  src/components/Auth/Login.tsx
  src/components/CommonHeader/CommonHeader.tsx
  src/components/CommonHeader/LogoutModal.tsx
  src/components/Dashboard/DashboardBody.tsx
  src/components/Dashboard/LatestProjects.tsx
  src/components/Dashboard/PerformanceGraph.tsx
  src/components/Dashboard/TaskStatusGraph.tsx
  src/components/Profile/CheckPasswordModal.tsx
  src/components/Profile/ProfileAccountInfo.tsx
  src/components/common/CommonFooter.tsx
  src/constant/TaskOverview.ts
  src/pages/admin.tsx
  src/pages/dashboard/index.tsx
  src/pages/join/[step].tsx
  src/pages/join/complete.tsx
  src/pages/login.tsx
  src/pages/profile/[id].tsx
  src/styles/auth.styles.ts
  src/utils/index.ts
  src/utils/serverAuth.ts
Labels: enhancement

#65 스켈레톤 컴포넌트 추가 및 코드 분리, 코드 수정, 무한스크롤
  src/apis/overview.ts
  src/components/Calendar/CalendarView.tsx
  src/components/CommonAvatar/CommonAvatar.tsx
  src/components/CommonHeader/CommonHeader.tsx
  src/components/OverView/Content.tsx
  src/components/OverView/Header.tsx
  src/components/Skeleton/index.tsx
  src/pages/tasks/index.tsx
  src/pages/tasks/period.tsx
  src/store/overViewStore.ts
  src/styles/overview.styles.ts
  src/type/componentProps.ts
Labels: enhancement

#67 [미 로그인 사용자 각 페이지 접근 제한]
  src/apis/dashboard.ts
  src/components/Admin/Admin.tsx
  src/components/Auth/Join/StepThree.tsx
  src/components/Auth/Join/StepTwo.tsx
  src/components/Auth/Login.tsx
  src/components/CommonAvatar/CommonAvatar.tsx
  src/components/Dashboard/LatestProjects.tsx
  src/components/Dashboard/LatestProjectsList.tsx
  src/components/Dashboard/TaskProjectsPerformance.tsx
  src/components/Dashboard/TaskStatus.tsx
  src/components/Dashboard/TaskStatusList.tsx
  src/components/Profile/ProfileAccountInfo.tsx
  src/components/common/CommonToast.tsx
  src/pages/admin.tsx
  src/pages/dashboard/index.tsx
  src/pages/join/[step].tsx
  src/pages/profile/[id].tsx
  src/store/userJoinStore.ts
  src/styles/dashboard.styles.ts
  src/type/enum/TaskStatusEnum.ts
  src/type/enum/TeamEnum.ts
  src/utils/index.ts
Labels: bug, enhancement

#75 feat: Calendar - 미 로그인 유저 접근 제한, calendar - 컴포넌트 명 수정
  src/components/CommonHeader/CommonHeader.tsx
  src/pages/calendar/index.tsx
  src/pages/index.tsx
Labels: bug, enhancement

#76 fix: [Admin, 프로필 업데이트 페이지] 수정
  src/components/Admin/Admin.tsx
  src/components/CommonHeader/CommonHeader.tsx
  src/components/Dashboard/LatestProjectsList.tsx
  src/components/Profile/ProfileAccountInfo.tsx
  src/components/Profile/ProfileRoleInfo.tsx
  src/components/common/CommonEmptyUser.tsx
  src/pages/admin.tsx
  src/pages/profile/[id].tsx
  src/styles/admin.styles.ts
  src/styles/dashboard.styles.ts
  src/styles/profile.styles.ts
Labels: bug, enhancement

#77 #74 , #69 이슈 작업
  src/apis/overview.ts
  src/components/Calendar/CalendarView.tsx
  src/components/CommonHeader/CommonHeader.tsx
  src/components/Drawer/index.tsx
  src/components/OverView/Content.tsx
  src/components/OverView/Header.tsx
  src/pages/calendar/index.tsx
  src/pages/index.tsx
  src/pages/tasks/index.tsx
  src/pages/tasks/period.tsx
  src/store/calendarStore.ts
  src/store/sideBarStore.ts
  src/styles/calendar.styles.ts
  src/styles/overview.styles.ts
  src/type/componentProps.ts
Labels: bug, enhancement

#79 fix: 로그인 후 로그인 라우팅이 안되는 오류
  src/components/Admin/Admin.tsx
  src/components/Auth/Join/StepThree.tsx
  src/components/Auth/Login.tsx
  src/components/CommonAvatar/CommonAvatar.tsx
  src/components/Dashboard/LatestProjectsList.tsx
  src/components/Dashboard/TaskStatusList.tsx
  src/components/Profile/ProfileAccountInfo.tsx
  src/components/kanban/KanbanDroppable.tsx
  src/pages/kanban.tsx
Labels: bug, enhancement

#80 #79 오류 수정 후 코드 최신화
  src/components/Admin/Admin.tsx
  src/components/Auth/Join/StepThree.tsx
  src/components/Auth/Login.tsx
  src/components/CommonAvatar/CommonAvatar.tsx
  src/components/Dashboard/LatestProjectsList.tsx
  src/components/Dashboard/TaskStatusList.tsx
  src/components/Profile/ProfileAccountInfo.tsx
  src/components/kanban/KanbanDroppable.tsx
  src/pages/kanban.tsx
Labels: bug, enhancement

#81 fix: router 수정
  src/components/Auth/Login.tsx
Labels: bug, enhancement

#86 feat: favicon, main Logo 교체, main Logo 클릭 시 calendar 페이지로 라우팅
  public/Logo.png
  public/favicon.ico
  public/next.svg
  public/thirteen.svg
  public/vercel.svg
  src/components/CommonHeader/CommonHeader.tsx
  src/styles/commonHeader.styles.ts
Labels: enhancement

#88 #70 , #85 이슈 작업
  public/png/sad.png
  src/apis/calendar.ts
  src/components/Calendar/CalendarView.tsx
  src/components/CommonHeader/CommonHeader.tsx
  src/components/OverView/Content.tsx
  src/components/OverView/Header.tsx
  src/components/OverView/index.tsx
  src/pages/404.tsx
  src/pages/tasks/index.tsx
  src/pages/tasks/period.tsx
  src/styles/notFound.styles.ts
  src/styles/overview.styles.ts
Labels: bug, enhancement

#89 fix: CalendarView - 다음 달 버튼 클릭 시, 다음 달 data가 fetching 되지 않는 오류 수정
  src/components/Calendar/CalendarView.tsx
Labels: bug, enhancement

#90 develop -> main 코드 최신화
  README.md
  public/Logo.png
  public/favicon.ico
  public/next.svg
  public/png/sad.png
  public/thirteen.svg
  public/vercel.svg
  src/apis/calendar.ts
  src/components/Calendar/CalendarView.tsx
  src/components/CommonHeader/CommonHeader.tsx
  src/components/OverView/Content.tsx
  src/components/OverView/Header.tsx
  src/components/OverView/index.tsx
  src/components/modal/CreateTask.tsx
  src/components/modal/ModalEditComponent.tsx
  src/components/modal/TaskOverview.tsx
  src/pages/404.tsx
  src/pages/kanban.tsx
  src/pages/tasks/index.tsx
  src/pages/tasks/period.tsx
  src/styles/commonHeader.styles.ts
  src/styles/notFound.styles.ts
  src/styles/overview.styles.ts
Labels: enhancement

#92 #91 이슈 작업
  src/components/Calendar/CalendarView.tsx
  src/components/CommonHeader/CommonHeader.tsx
  src/components/OverView/Content.tsx
  src/components/OverView/index.tsx
Labels: enhancement

#94 코드 주석, readme 수정
  README.md
  exam/img_2.png
  exam/img_3.png
  exam/img_4.png
  src/apis/overview.ts
  src/components/Calendar/CalendarView.tsx
  src/components/OverView/Content.tsx
  src/components/OverView/Header.tsx
  src/components/OverView/index.tsx
Labels: enhancement

#98 일정 상세보기 progress 버그 수정
  package.json
  src/components/Drawer/index.tsx
  src/components/OverView/Content.tsx
  src/components/OverView/Header.tsx
  src/store/overViewStore.ts
Labels: bug

#99 Develop -> main 최신화
  package.json
  src/components/Drawer/index.tsx
  src/components/OverView/Content.tsx
  src/components/OverView/Header.tsx
  src/store/overViewStore.ts
Labels: enhancement

#100 사이트 성능 개선, 분석 도구 추가
  next.config.js
  package.json
  src/components/Drawer/index.tsx
  src/components/OverView/Header.tsx
  src/constant/TaskOverview.ts
  src/pages/admin.tsx
  src/pages/api/hello.ts
  src/pages/join/[step].tsx
  src/store/store.ts
  src/styles/Fonts.tsx
  src/styles/globals.css
  src/type/stroeType.ts
Labels: enhancement

#102 readme 업데이트
  README.md
  exam/img_2.png
  exam/img_3-1.png
  exam/img_3.png
Labels: documentation
